name: Maven Package

on:
  push:
    branches:
      - master  # Or your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'  # Eclipse Temurin is a widely used distribution

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy
      env:
        GITHUB_TOKEN: "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"
